# A minimum set of schema mappings required for the ontology ingestion
schema:
    id: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    parent: https://vocabs.acdh.oeaw.ac.at/schema#isPartOf
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    delete: delete://delete
    searchMatch: search://match
    hash: https://vocabs.acdh.oeaw.ac.at/schema#hasHash
    accessRestriction: https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestriction
    previous: https://vocabs.acdh.oeaw.ac.at/schema#isPreviousVersionOf
    namespaces:
        ontology: https://vocabs.acdh.oeaw.ac.at/schema#
        id: https://id.acdh.oeaw.ac.at/
    ontology:
        order: https://vocabs.acdh.oeaw.ac.at/schema#ordering
        recommended: https://vocabs.acdh.oeaw.ac.at/schema#recommendedClass
        langTag: https://vocabs.acdh.oeaw.ac.at/schema#langTag
        vocabs: https://vocabs.acdh.oeaw.ac.at/schema#vocabs
        dateStart: https://vocabs.acdh.oeaw.ac.at/schema#hasCreatedStartDate
        dateEnd: https://vocabs.acdh.oeaw.ac.at/schema#hasCreatedEndDate
        url: https://vocabs.acdh.oeaw.ac.at/schema#hasUrl
        version: https://vocabs.acdh.oeaw.ac.at/schema#hasVersion
        info: https://vocabs.acdh.oeaw.ac.at/schema#hasVersionInfo
