rest:
    urlBase: http://127.0.0.1
    pathBase: /api/
    headers:
        metadataReadMode: X-METADATA-READ-MODE
        metadataParentProperty: X-PARENT-PROPERTY
        metadataWriteMode: X-METADATA-WRITE-MODE
        transactionId: X-TRANSACTION-ID
schema:
    id: https://vocabs.acdh.oeaw.ac.at/schema#hasIdentifier
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    parent: https://vocabs.acdh.oeaw.ac.at/schema#isPartOf
    label: https://vocabs.acdh.oeaw.ac.at/schema#hasTitle
    delete: delete://delete
    searchMatch: search://match
    hash: https://vocabs.acdh.oeaw.ac.at/schema#hasHash
    accessRestriction: https://vocabs.acdh.oeaw.ac.at/schema#hasAccessRestriction
    previous: https://vocabs.acdh.oeaw.ac.at/schema#isPreviousVersionOf
    namespaces:
        ontology: https://vocabs.acdh.oeaw.ac.at/schema#
        id: https://id.acdh.oeaw.ac.at/
    ontology:
        order: https://vocabs.acdh.oeaw.ac.at/schema#ordering
        recommended: https://vocabs.acdh.oeaw.ac.at/schema#recommendedClass
        langTag: https://vocabs.acdh.oeaw.ac.at/schema#langTag
        vocabs: https://vocabs.acdh.oeaw.ac.at/schema#vocabs
auth:
    httpBasic:
        user: ''
        password: ''

